name: Deploy Spring Boot App to EC2 (Amazon Linux)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    - name: Add EC2 to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy Spring Boot to EC2
      run: |
        ssh -i ~/.ssh/id_rsa ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          set -e
          echo "Entrando al directorio de la app"
          cd /home/ec2-user/law-office

          echo "Haciendo pull del último código"
          git pull origin main

          echo "Compilando la app con Gradle"
          ./gradlew build -x test

          echo "Deteniendo el proceso anterior"
          pkill -f '.jar' || true

          echo "Ejecutando nueva versión"
          nohup java -jar build/libs/*.jar > app.log 2>&1 &

          echo "Despliegue completo"
        EOF
